databases:
  - name: Tarutani DataBase
    databaseName: tarutani_database
    user: TarutaniApp
    region: singapore

services:
  - type: web
    name: TarutaniApp
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Tarutani DataBase
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

